# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Schematics CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run build --if-present
    - run: git config --global user.email "edu@arkerlabs.com"
    - run: git config --global user.name "Eduardo Simón"
    - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
    - run: npm run release -- --ci  --verbose
      env: 
        CI: true
        GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN }}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
