# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Schematics CI

on:
  push:
    branches: [ master, '+([0-9])?(.{+([0-9]),x}).x', 'next' ]
  pull_request:
    branches: [ master, '+([0-9])?(.{+([0-9]),x}).x', 'next' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: git config --global user.email "edu@arkerlabs.com"
    - run: git config --global user.name "Eduardo Simón"

    - run: npm run release
      env: 
        CI: true
        GITHUB_TOKEN: ${{ secrets.RELEASE_IT_GITHUB_TOKEN }}
        GH_TOKEN: ${{secrets.GH_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
        
